sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm install
  - npm run lint
script:
  - npm run test
  - npm run coverage
after_success:
   - npm run serve
  