sudo: false
language: node_js
node_js:
  - "8"
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm install
script:
  - npm lint
  - npm run watch
 after_success:
   - now run serve
  